### PR TITLE
Fixes incorrect behavior of session context menu

### LINKED ISSUE #347: Context menu doesn't handle watched/unwatched correctly
### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS: 10.13.3
- Version of the app: 5.3
- If it is a wrong behavior, list all steps required to reproduce it
When you watch a video, the context menu will never treat the video as "watched" even if you watch it to the absolute end.

Expectation: Videos filtered out by the "unwatched" filter should also show "Mark as Unwatched" in the context menu.

note: The "Mark as Unwatched" will be activated if you first "Mark as Watched" which will set the relative progress to exactly 1. While the playback time observer sets the progress to things like 0.998868563034773 and 1.00000097433287.

I believe the context menu should use the same threshold as the "unwatched" filter, which is 0.9. This could be achieved by adding an `isWatched` non-stored property to `Session` to encapsulate the handling. It also looks like the relative position could use a little extra math to cap it at 1.0 and possibly do a little rounding?

### PR DESCRIPTION
**Pull request by allenhumphreys**
Fixes #347 

It turns out there was a constant already defined, it's value is 0.97.

### CODE REVIEW

File: WWDC/SessionsTableViewController.swift [hunk 1]
```diff
@@ -497,6 +501,17 @@ class SessionsTableViewController: NSViewController {
     }
 }
 
+extension Session {
+
+    var isWatched: Bool {
```
Comment (allenhumphreys) [inline WWDC/SessionsTableViewController.swift]: In your opinion, where should this live @insidegui ? The `Constants` are part of WWDC, while `Session` is part of ConfCore. So it feels fine as an extension defined in WWDC but could probably use a better home.

Comment (insidegui) [reply WWDC/SessionsTableViewController.swift]: Interesting question. I think we can leave it as is by now, but maybe some constants should be moved into ConfCore (or have some entity in ConfCore that can hold these types of configurations).
